### ISSUE TITLE
TO-DO v2.0

### ISSUE THREAD

**Issue by SuperKali** [SuperKali/CustomBar#7]
TO-DO LIST:
- [x] support command for show and hide HUD
- [ ] support for move HUD anywhere
- [x] ping colour for high ping ' RED ' low ping ' GREEN ' on HUD

**Comment by Emis02** [comment]
Buon tonno aggiungi economy all hud😉

**Comment by Emis02** [comment]
Hi, cool plugin. Can you add economy at this plugin pls?

**Comment by SuperKali** [comment]
@Emis02 EconomyAPI added

**Comment by Emis02** [comment]
Aggiungi faction Pro e clan http://github.com/Emis02/Clans-ITA

**Comment by mote166** [comment]
Can u add timezones support?

**Comment by SuperKali** [comment]
@mote166 ok

**Comment by Eris11qo** [comment]
add {time} with different Time Zone

**Comment by timbersquirrel** [comment]
Add /hud on/off

**Comment by SuperKali** [comment]
@timbersquirrel ok, i add the command in this week

**Comment by timbersquirrel** [comment]
Thanks

**Comment by BurritoMan46** [comment]
Add {rank} so we can see our rank on Hud

**Comment by BajanVlogs** [comment]
add where we can move the hud anywhere on the screen

**Comment by ErkamKahriman** [comment]
Add Support for Turanic xD

**Comment by SuperKali** [comment]
@ErkamKahriman already is supported of turanic

**Comment by SuperKali** [comment]
@BurritoMan46 ok, i will push tonight the update, for PureChat Ranks

**Comment by SuperKali** [comment]
@BajanVlogs i will add this soon

**Comment by SpecialistNinja** [comment]
@SuperKali Add coord

**Comment by SpecialistNinja** [comment]
/hud reload can be done in game without restarting the whole server to see the changes

**Comment by SuperKali** [comment]
@SpecialistNinja I will add now

**Comment by SuperKali** [comment]
@SpecialistNinja https://github.com/SuperKali/CustomBar/commit/8e79f5c2a21a7af4dc5c1e78bc872c52aa1812fb added on this commit, will try a test and for all problem contact here

**Comment by Nodico** [comment]
KillChat plugin please? And GameTime?

**Comment by TDMidkwhatisxd** [comment]
customhud command crash , and customhud reload just reset config to original, weird

**Comment by SuperKali** [comment]
@Nodico Killchat implemented, if you can that i implement on this customhud send me the plugin GameTime
